//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgFarmes.Models
{
    using System;
    using System.Collections.Generic;
    
    //farmer_products is a link table for farmer and products
    public partial class farmer_product
    {
        //below are the gets and sets for farmer_product table
        public int FarmerID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual farm_products farm_products { get; set; }
        public virtual Farmer Farmer { get; set; }
    }
}
//--------------------------------------End of File -----------------------------------//

