//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgFarmes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VC_PROG7311_ST10081886Entities1 : DbContext
    {
        public DB_VC_PROG7311_ST10081886Entities1()
            : base("name=DB_VC_PROG7311_ST10081886Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<farm_products> farm_products { get; set; }
        public DbSet<Farmer> Farmers { get; set; }
        public DbSet<farmer_product> farmer_product { get; set; }
    }
}
